# Generated by Django 3.0.8 on 2020-07-12 10:30

from django.db import migrations, models
import django.db.models.deletion
import vetmanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='FirstName')),
                ('midname', models.CharField(blank=True, max_length=50, verbose_name='MidName')),
                ('lastname', models.CharField(max_length=50, verbose_name='LastName')),
                ('clientpic', models.ImageField(default='Default.jpg', max_length=255, upload_to=vetmanagement.models.VetClient.photo_path, verbose_name='Client Picture')),
                ('address', models.TextField(verbose_name='Address')),
                ('streetaddress', models.CharField(max_length=100, verbose_name='Street Address')),
                ('addressline2', models.TextField(blank=True, verbose_name='AddressLine2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='State')),
                ('zip', models.CharField(max_length=20, verbose_name='Zip')),
                ('homephone', models.CharField(blank=True, max_length=30, verbose_name='Home Phone')),
                ('workphone', models.CharField(blank=True, max_length=30)),
                ('cellphone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('employer', models.CharField(blank=True, max_length=100)),
                ('hearaboutus', models.CharField(choices=[('Google', 'Google'), ('Yellow Pages', 'Yellow Pages'), ('Walk-in', 'Walk-in'), ('Other', 'Other')], default='Google', max_length=30)),
                ('refvet', models.CharField(blank=True, max_length=100)),
                ('familyvet', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VetPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100, verbose_name='Pet Name')),
                ('petpic', models.ImageField(default='Default.jpg', upload_to=vetmanagement.models.VetPet.photo_path, verbose_name='Pet Picture')),
                ('species', models.CharField(choices=[('Canine', 'Canine'), ('Feline', 'Feline'), ('Other', 'Other')], default='Canine', max_length=20, verbose_name='Species')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male Neutered', 'Male Neutered'), ('Female Spayed', 'Female Spayed')], default='Male', max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('initproblem', models.TextField(verbose_name='Initial Problem')),
                ('picauthorization', models.BooleanField(default=False, verbose_name='Picture Authorization')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('vet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='vetmanagement.VetClient', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='VetClientOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='vetmanagement.VetClient')),
            ],
        ),
    ]
