# Generated by Django 3.0.8 on 2020-07-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import managevet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=100, verbose_name='Pet Name')),
                ('petpic', models.ImageField(blank=True, default='Default.jpg', upload_to=managevet.models.Pet.petphoto_path, verbose_name='Pet Picture')),
                ('species', models.CharField(choices=[('Canine', 'Canine'), ('Feline', 'Feline'), ('Other', 'Other')], default='Canine', max_length=20, verbose_name='Species')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male Neutered', 'Male Neutered'), ('Female Spayed', 'Female Spayed')], default='Male', max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('initproblem', models.TextField(blank=True, verbose_name='Initial Problem')),
                ('picauthorization', models.BooleanField(default=False, verbose_name='Picture Authorization')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('petuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petuser', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_dist_parvo_corona', models.CharField(blank=True, max_length=50, verbose_name='Dog:Distemper/Parvo/Corona')),
                ('dog_leptospirosis', models.CharField(blank=True, max_length=50, verbose_name='Dog:Leptospirosis?')),
                ('dog_rabies', models.CharField(blank=True, max_length=50, verbose_name='Dog:Rabies?')),
                ('dog_bordatella', models.CharField(blank=True, max_length=50, verbose_name='Dog:Bordatella?')),
                ('cat_panleukopenia_rhinotracheitis_calicivirus', models.CharField(blank=True, max_length=50, verbose_name='Cat:Panleukopenia/Rhinotracheitis/Calicivirus?')),
                ('cat_rabies', models.CharField(blank=True, max_length=50, verbose_name='Cat:Rabies?')),
                ('cat_feline_leukemia_virus', models.CharField(blank=True, max_length=50, verbose_name='Cat: Feline Leukemia Virus (FeLV)?')),
                ('cat_feline_immunodeficiency_virus', models.CharField(blank=True, max_length=50, verbose_name='Cat: Feline Immunodeficiency Virus (FIV, feline, AIDS)?')),
                ('treated_any_medical_problems', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Prior to this illness, has your pet been treated for any medical problems?')),
                ('age_when_surgery_performed', models.CharField(blank=True, max_length=10, verbose_name='If your pet is neutered/spayed, what was his/her age when this surgery was performed?')),
                ('any_other_surgery', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet undergone any other surgery?')),
                ('female_any_litters', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='If your pet is female has she had any litters?')),
                ('female_last_heat_cycle', models.CharField(blank=True, max_length=50, verbose_name='If your pet is female and not spayed, when was her last heat cycle?')),
                ('abnormal_vaginal_discharge', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='If your pet is female, has there been any abnormal vaginal discharge?')),
                ('medication_for_heatwork_disease', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet taking medicine to prevent heatwork disease?')),
                ('medication_for_fleas', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet now taking medicine to prevent fleas?')),
                ('medication_for_ticks', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet taking medicine to prevent ticks?')),
                ('traveled_out_of_mexico', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet traveled out of New Mexico?')),
                ('normally_eat', models.CharField(max_length=100)),
                ('howmuch_howoften_eat', models.CharField(max_length=100)),
                ('ever_fed_table_scraps', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet ever fed table scraps?')),
                ('appetite_increased_decreased', models.CharField(choices=[('Increased', 'Increased'), ('Decreased', 'Decreased'), ('No Change', 'No Change')], default='Increased', max_length=10, verbose_name="Has your pet's diet increased decreased recently?")),
                ('drinking_more_water', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No Change', 'No Change')], default='No', max_length=10, verbose_name='Is your pet drinking more water than usual?')),
                ('urinating_more_than_usual', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet urinating more than usual?')),
                ('straining_to_urinate', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet straining to urinate?')),
                ('blood_or_discolouration_urine', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name="Is there any blood or discoloration of your pet's urine?")),
                ('vomiting', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet been vomiting?')),
                ('change_in_bowl_moments', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name="Have there been any recent changes in the frequency, amount or color of your pet's bowel movements?")),
                ('straining_to_defecate', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Is your pet straining to defecate?')),
                ('itching_or_scratching', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet been itching or scratching?')),
                ('discharge_from_eyes_nose', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet had any discharge from eyes or nose?')),
                ('sneezing_excessively', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet been sneezing excessively?')),
                ('coughing_difficulty_breating', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet been coughing or showing difficulty breathing?')),
                ('seizures_or_convulsions', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet had any seizures or convulsions?')),
                ('change_attitude_behavior', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet shown any change in attitude or behavior?')),
                ('lost_stamina_recently', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet lost stamina recently?')),
                ('walk_changed', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name="Has your pet's walk changed?")),
                ('noticed_swelling_or_masses', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Have you noticed any swelling or masses?')),
                ('unusual_reaction_to_medications', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='No', max_length=10, verbose_name='Has your pet had unusual/unexpected reactions to medications?')),
                ('current_medication', models.TextField()),
                ('primary_concern', models.TextField()),
                ('petpic', models.ImageField(blank=True, upload_to=managevet.models.VaccinationHistory.petfile_path, verbose_name='Pet Picture')),
                ('vaccination_history', models.FileField(upload_to='')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managevet.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='FirstName')),
                ('midname', models.CharField(blank=True, max_length=50, verbose_name='MidName')),
                ('lastname', models.CharField(max_length=50, verbose_name='LastName')),
                ('usertpic', models.ImageField(blank=True, default='Default.jpg', max_length=255, upload_to=managevet.models.Profile.userphoto_path, verbose_name='User Picture')),
                ('address', models.TextField(default='', verbose_name='Address')),
                ('streetaddress', models.CharField(default='', max_length=100, verbose_name='Street Address')),
                ('addressline2', models.TextField(blank=True, verbose_name='AddressLine2')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='State')),
                ('zip', models.CharField(max_length=20, verbose_name='Zip')),
                ('homephone', models.CharField(blank=True, max_length=30, verbose_name='Home Phone')),
                ('workphone', models.CharField(blank=True, max_length=30)),
                ('cellphone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('employer', models.CharField(blank=True, max_length=100)),
                ('hearaboutus', models.CharField(choices=[('Google', 'Google'), ('Yellow Pages', 'Yellow Pages'), ('Walk-in', 'Walk-in'), ('Other', 'Other')], default='Google', max_length=30)),
                ('refvet', models.CharField(blank=True, max_length=100)),
                ('familyvet', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagereceiver', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('petowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petowner', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_pet_owned', models.CharField(default='0', max_length=100, verbose_name='How long have you owned your pet?')),
                ('pet_obtained', models.CharField(max_length=100, verbose_name='Where was your pet obtained?')),
                ('pet_allowed_outside', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='Yes', max_length=10, verbose_name='Does your pet ever go outside?')),
                ('pet_allowed_roam_free', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='Yes', max_length=10, verbose_name='Is your pet allowed to roam free?')),
                ('board_hosp_animal_shelter', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='Yes', max_length=10, verbose_name='Has your pet been boarded, hospitalized or at the animal shelter recently?')),
                ('any_other_household', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='Yes', max_length=10, verbose_name='Are there any other animals in your household?')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managevet.Pet')),
            ],
        ),
    ]
